[package]
name = "wordle-riddle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.17", features = ["derive"] }
fnv = "1.0.7"
num-bigint = "0.4.3"
rayon = "1.5.3"
